### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by steinbrueckri** [YSmetana/zabbix-mikrotik-snmp#2]
ERROR: Import failed - XML file contains fatal error 77:Premature end of data in tag item line 129 [ Line: 133 | Column: 1 ]

**Comment by YuriySm** [comment]
I am sorry about that.. File reuploaded. Can you try it again?

**Comment by steinbrueckri** [comment]
Now it's working. By the Way thx for you work :+1: :+1:
