### ISSUE TITLE
I cant Import

### ISSUE THREAD

**Issue by Filipe-Mariano** [YSmetana/zabbix-mikrotik-snmp#3]
Hi, im Brasilian em new in zabbix, can u help me?

details
ERROR: Import failed
The XML file contains a fatal error 41: Specification mandate value for attribute data-pjax-transient [Line: 32 | Column: 40]

**Comment by YuriySm** [comment]
Oi! 

Please double check that you have downloaded raw-version of the file (code only):

![RAW file](http://i6.5cm.ru/i/ZX2P.png)

https://raw.githubusercontent.com/YSmetana/zabbix-mikrotik-snmp/master/template_snmp/zbx_export_templates.xml

Or download ZIP https://github.com/YSmetana/zabbix-mikrotik-snmp/archive/master.zip and **extract** XML template from there.

**Comment by Filipe-Mariano** [comment]
thanks :*

**Comment by YuriySm** [comment]
;)
